project 'BasicUI.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BasicUI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BasicUI
  pod 'MJRefresh'
  pod 'Masonry'
  pod 'OpenUDID'
  pod 'SDWebImage'

  target 'BasicUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BasicUIUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
